-- local dap = require("dap")
-- local dapui = require("dapui")
--
-- -- require("dap-python").setup("~/.venv/bin/python")
-- require("dap-python").setup("python")
--
-- dapui.setup()
--
-- dap.listeners.before.attach.dapui_config = function() dapui.open() end
-- dap.listeners.before.launch.dapui_config = function() dapui.open() end
-- dap.listeners.before.event_terminated.dapui_config = function()
--   dapui.close()
-- end
-- dap.listeners.before.event_exited.dapui_config = function()
--   dapui.close()
-- end
